"""
sanity_tracial.py -- end-to-end numerical sanity check of a max-ent certificate on RANDOM strategies:
take random order-d unitaries R_1..R_4 on C^D, build the symmetrised strategy (direct sum of all images
under the group generated by rho, sigma, transpose), and compare
     S(Rbar) - lam      with      sum_b sum_ij X_ij tau(e_j^+ e_i)(Rbar)      (X = N Y N^+ from the file).
They must agree (identity modulo the symmetry relations) and be >= 0.
"""
import sys
import pickle
import numpy as np
from cyclo import Field


def rand_order_d_unitary(d, D, rng):
    Z = rng.normal(size=(D, D)) + 1j * rng.normal(size=(D, D))
    Q, _ = np.linalg.qr(Z)
    labels = rng.integers(0, d, size=D)
    w = np.exp(2j * np.pi * labels / d)
    return (Q * w) @ Q.conj().T


def images(R, d):
    w = np.exp(2j * np.pi / d)
    inv = lambda M: M.conj().T
    def key(T):
        return tuple(np.round(np.concatenate([M.ravel() for M in T]), 8).tolist()[:6])
    out = []
    seen = []
    stack = [tuple(R)]
    while stack:
        T = stack.pop()
        if any(all(np.allclose(a, b) for a, b in zip(T, U)) for U in seen):
            continue
        seen.append(T)
        stack.append((T[1], T[2], T[3], w * T[0]))                    # rho
        stack.append((inv(T[3]), inv(T[2]), inv(T[1]), inv(T[0])))    # sigma
        stack.append(tuple(M.T for M in T))                            # transpose (reversal)
        if len(seen) > 400:
            break
    return seen


def S_val(R, d):
    w = np.exp(2j * np.pi / d)
    mp = np.linalg.matrix_power
    tau = lambda M: np.trace(M) / M.shape[0]
    S = 2 * (d - 1)
    for n in range(1, d):
        c = -1 / (1 - w ** (-n))
        S += c * (tau(mp(R[0], n) @ mp(R[1], -n)) + tau(mp(R[1], n) @ mp(R[2], -n))
                  + tau(mp(R[2], n) @ mp(R[3], -n)) + w ** (-n) * tau(mp(R[3], n) @ mp(R[0], -n)))
    return S.real


def word_mat(R, w, d):
    M = np.eye(R[0].shape[0], dtype=complex)
    for (g, n) in w:
        M = M @ np.linalg.matrix_power(R[g], n % d)
    return M


if __name__ == "__main__":
    d = int(sys.argv[1])
    D = int(sys.argv[2]) if len(sys.argv) > 2 else d + 2
    cert = pickle.load(open(f"cert_tracial_d{d}.pkl", "rb"))
    F = Field(4 * d)
    lam = F.to_cfloat(cert["lam"]).real
    rng = np.random.default_rng(5)
    for trial in range(3):
        R = [rand_order_d_unitary(d, D, rng) for _ in range(4)]
        imgs = images(R, d)
        # symmetrised functional = average over images
        Sbar = np.mean([S_val(T, d) for T in imgs])
        tot = 0.0
        for b in cert["keep"]:
            lab, els, _ = cert["bdata"][b]
            N = np.array([[F.to_cfloat(x) for x in col] for col in cert["kernels"][b]]).T
            Y = np.array([[F.to_cfloat(x) for x in row] for row in cert["Y"][b]])
            X = N @ Y @ N.conj().T
            els_c = [[(F.to_cfloat(c), w) for (c, w) in el] for el in els]
            for T in imgs:
                E = [sum(c * word_mat(T, w, d) for (c, w) in el) for el in els_c]
                n = len(E)
                G = np.array([[np.trace(E[j].conj().T @ E[i]) / D for i in range(n)] for j in range(n)])
                tot += np.real(np.sum(X * G.T)) / len(imgs)
        print(f"d={d} D={D} trial {trial}: #images {len(imgs)}  S(sym) - lam = {Sbar - lam:.10f}   "
              f"SOS value = {tot:.10f}   diff = {Sbar - lam - tot:.2e}", flush=True)
