"""
verify_bip.py -- INDEPENDENT exact checker for the all-states CGLMP certificates cert_bip_d{d}.pkl
(NPA level 1+AB, symmetry reduced).  Uses only verify_tracial.CF (Fraction-based cyclotomic field)
and re-implements the extension field, word algebra and symmetry canonicalisation.

Claim verified (for the given d): for every bipartite quantum strategy (any state, any dimension,
projective d-outcome measurements; POVMs by Naimark dilation)
    S = E m(X1-Y1) + E m(Y1-X2) + E m(X2-Y2) + E m(Y2-X1-1) >= 2d - 1 - lambda_max(K_d),
equivalently I_d <= 2(lambda_max(K_d) - 1)/(d-1)  (the Acin-Durt-Gisin-Latorre value), with equality
for the DKZ measurements and psi = sum_k v_k |kk>, v the Perron vector of K_d = [sec(pi(k-l)/(2d))].
Checked:
 (1) exact identity S_op - lam = sum_b sum_ij (N_b Y_b N_b^+)_ij e_j^+ e_i in the algebra generated by
     commuting Alice/Bob unitaries of order d, modulo the symmetry relations (reversal, rho, sigma
     with party swap); S_op invariant under these (checked);
 (2) Y_b positive definite (exact LDL over L = Q(zeta_{4d})[t]/p(t), pivot signs by interval
     arithmetic at the certified real root t = lambda*);
 (3) lambda* = lambda_max(K_d) and attainment: the DKZ Bell operator restricted to span{|kk>} equals
     (2d-1) 1 - K_d exactly and leaves that span invariant.
"""
import sys
import pickle
from fractions import Fraction
import mpmath as mp
from verify_tracial import CF, from_cyclo, reduce_w, adj


class LF:
    """L = K[t]/(p), K = CF, p monic with real coefficients."""

    def __init__(self, K, p):
        self.K = K
        self.p = p
        self.m = len(p) - 1

    def zero(self):
        return tuple(self.K.zero() for _ in range(self.m))

    def fromK(self, a):
        return tuple([a] + [self.K.zero() for _ in range(self.m - 1)])

    def t(self):
        return tuple([self.K.zero(), self.K.const(1)] + [self.K.zero() for _ in range(self.m - 2)])

    def iszero(self, x):
        return all(self.K.iszero(a) for a in x)

    def add(self, x, y):
        return tuple(self.K.add(a, b) for a, b in zip(x, y))

    def sub(self, x, y):
        return tuple(self.K.sub(a, b) for a, b in zip(x, y))

    def mul(self, x, y):
        K, m = self.K, self.m
        prod = [K.zero() for _ in range(2 * m - 1)]
        for i, a in enumerate(x):
            if K.iszero(a):
                continue
            for j, b in enumerate(y):
                if not K.iszero(b):
                    prod[i + j] = K.add(prod[i + j], K.mul(a, b))
        for k in range(2 * m - 2, m - 1, -1):
            c = prod[k]
            if K.iszero(c):
                continue
            prod[k] = K.zero()
            for j in range(m):
                prod[k - m + j] = K.sub(prod[k - m + j], K.mul(c, self.p[j]))
        return tuple(prod[:m])

    def conj(self, x):
        return tuple(self.K.conj(a) for a in x)

    def inv(self, x):
        K, m = self.K, self.m
        cols = []
        e = tuple([K.const(1)] + [K.zero() for _ in range(m - 1)])
        for k in range(m):
            cols.append(self.mul(x, e))
            e = self.mul(e, self.t())
        A = [[cols[j][i] for j in range(m)] + [K.const(1) if i == 0 else K.zero()] for i in range(m)]
        for c in range(m):
            pr = next(r for r in range(c, m) if not K.iszero(A[r][c]))
            A[c], A[pr] = A[pr], A[c]
            iv = K.inv(A[c][c])
            A[c] = [K.mul(v, iv) for v in A[c]]
            for r in range(m):
                if r != c and not K.iszero(A[r][c]):
                    f = A[r][c]
                    A[r] = [K.sub(vr, K.mul(f, vc)) for vr, vc in zip(A[r], A[c])]
        return tuple(A[i][m] for i in range(m))

    def interval(self, x, tiv):
        re = mp.iv.mpf(0)
        im = mp.iv.mpf(0)
        pw = mp.iv.mpf(1)
        for a in x:
            r, i = self.K.interval(a)
            re += r * pw
            im += i * pw
            pw = pw * tiv
        return re, im


def conv_L(K, x):
    return tuple(from_cyclo(K, a) for a in x)


class SymB:
    """canonical classes for bipartite moments L(a,b) under reversal, rho, sigma (party-swapping)."""

    def __init__(self, d):
        self.d, self.N = d, 4 * d
        self.memo = {}

    def subst(self, w, kind):
        d = self.d
        e, out = 0, []
        for (g, n) in w:
            if kind == 'rho':
                if g == 3:
                    e += 4 * n
                    out.append((0, n))
                else:
                    out.append((g + 1, n))
            else:
                out.append((3 - g, (-n) % d))
        return e, tuple(out)

    def gens(self, u):
        a, b = u
        d, N = self.d, self.N
        out = [(0, (reduce_w(tuple(reversed(a)), d), reduce_w(tuple(reversed(b)), d)))]
        for kind in ('rho', 'sigma'):
            e1, a1 = self.subst(a, kind)
            e2, b1 = self.subst(b, kind)
            out.append(((e1 + e2) % N, (reduce_w(b1, d), reduce_w(a1, d))))
        return out

    def __call__(self, u):
        d, N = self.d, self.N
        u = (reduce_w(u[0], d), reduce_w(u[1], d))
        if u in self.memo:
            return self.memo[u]
        seen = {u: 0}
        stack = [u]
        bad = False
        while stack:
            x = stack.pop()
            for (e, y) in self.gens(x):
                ey = (seen[x] + e) % N
                if y in seen:
                    if seen[y] != ey:
                        bad = True
                else:
                    seen[y] = ey
                    stack.append(y)
        if bad:
            for x in seen:
                self.memo[x] = None
            return None
        rep = min(seen)
        for x, ex in seen.items():
            self.memo[x] = ((seen[rep] - ex) % N, rep)
        return self.memo[u]


WORKERS = 1
_CACHE = {}


def _load(d):
    if d not in _CACHE:
        cert = pickle.load(open(f"cert_bip_d{d}.pkl", "rb"))
        K = CF(4 * d)
        p = [from_cyclo(K, c) for c in cert["p"]]
        _CACHE[d] = (cert, K, LF(K, p))
    return _CACHE[d]


def _block_expand(args):
    d, b = args
    cert, K, L = _load(d)
    canon = SymB(d)
    P = {}
    def add(acc, u, c):
        r = canon(u)
        if r is None or L.iszero(c):
            return
        e, rep = r
        acc[rep] = L.add(acc.get(rep, L.zero()), L.mul(c, L.fromK(K.zpow(e))))
    lab, els, _ = cert["bdata"][b]
    ker = [[conv_L(K, x) for x in col] for col in cert["kernels"][b]]
    Y = [[conv_L(K, x) for x in row] for row in cert["Y"][b]]
    k, n = len(ker), len(els)
    for i in range(k):
        for j in range(k):
            assert L.iszero(L.sub(Y[i][j], L.conj(Y[j][i]))), "Y not Hermitian"
    NY = [[L.zero() for _ in range(k)] for _ in range(n)]
    for a_ in range(n):
        for c in range(k):
            acc = L.zero()
            for r in range(k):
                if not L.iszero(ker[r][a_]) and not L.iszero(Y[r][c]):
                    acc = L.add(acc, L.mul(ker[r][a_], Y[r][c]))
            NY[a_][c] = acc
    X = [[L.zero() for _ in range(n)] for _ in range(n)]
    for a_ in range(n):
        for bb in range(n):
            acc = L.zero()
            for c in range(k):
                if not L.iszero(NY[a_][c]) and not L.iszero(ker[c][bb]):
                    acc = L.add(acc, L.mul(NY[a_][c], L.conj(ker[c][bb])))
            X[a_][bb] = acc
    elsK = [[(from_cyclo(K, c), w) for (c, w) in el] for el in els]
    nterms = 0
    for i in range(n):
        for j in range(n):
            if L.iszero(X[i][j]):
                continue
            for (cj, (aj, bj)) in elsK[j]:
                for (ci, (ai, bi)) in elsK[i]:
                    c = L.mul(X[i][j], L.fromK(K.mul(K.conj(cj), ci)))
                    add(P, (reduce_w(adj(aj, d) + ai, d), reduce_w(adj(bj, d) + bi, d)), c)
                    nterms += 1
    return P, nterms


def _block_ldl(args):
    d, b, lam_str = args
    cert, K, L = _load(d)
    mp.mp.dps = 90
    mp.iv.prec = 320
    lam_num = mp.mpf(lam_str)
    eps = mp.mpf(10) ** -70
    tiv = mp.iv.mpf([lam_num - eps, lam_num + eps])
    Y = [[conv_L(K, x) for x in row] for row in cert["Y"][b]]
    k = len(Y)
    A = [list(r) for r in Y]
    minpiv = None
    for c in range(k):
        pv = A[c][c]
        assert L.iszero(L.sub(pv, L.conj(pv))), "pivot not real"
        re, im = L.interval(pv, tiv)
        assert re.a > 0, f"pivot not certified positive (block {b})"
        minpiv = float(re.a) if minpiv is None else min(minpiv, float(re.a))
        ip = L.inv(pv)
        for r in range(c + 1, k):
            if L.iszero(A[r][c]):
                continue
            f = L.mul(A[r][c], ip)
            for j in range(c + 1, k):
                if not L.iszero(A[c][j]):
                    A[r][j] = L.sub(A[r][j], L.mul(f, A[c][j]))
    return minpiv


def verify(d):
    cert = pickle.load(open(f"cert_bip_d{d}.pkl", "rb"))
    N = 4 * d
    K = CF(N)
    p = [from_cyclo(K, c) for c in cert["p"]]
    L = LF(K, p)
    for c in p:
        assert K.iszero(K.sub(c, K.conj(c))), "p not real"
    # rigorous enclosure of lambda* : largest real root of p, compared with lambda_max(K_d)
    mp.mp.dps = 90
    Kd = mp.matrix(d, d)
    for i in range(d):
        for j in range(d):
            Kd[i, j] = mp.sec(mp.pi * (i - j) / (2 * d))
    lam_num = max(mp.eigsy(Kd)[0])
    mp.iv.prec = 320
    eps = mp.mpf(10) ** -70
    lo, hi = mp.iv.mpf(lam_num - eps), mp.iv.mpf(lam_num + eps)
    def p_at(tv):
        acc = mp.iv.mpf(0)
        pw = mp.iv.mpf(1)
        for c in p:
            r, _ = K.interval(c, 320)
            acc += r * pw
            pw = pw * tv
        return acc
    plo, phi = p_at(lo), p_at(hi)
    assert (plo.b < 0 < phi.a) or (phi.b < 0 < plo.a), "root of p not isolated near lambda_max(K_d)"
    tiv = mp.iv.mpf([lam_num - eps, lam_num + eps])
    # (a) lambda_max(K_d) is a root of p and is the largest root: check p has no root above hi
    #     (Cauchy-type check: numerically all roots of p are <= lam_num + eps)
    pc = [mp.mpf(mp.iv.mpf(K.interval(c, 320)[0]).mid) for c in p]
    roots = mp.polyroots(list(reversed(pc)), maxsteps=300, extraprec=300)
    assert max(mp.re(r) for r in roots) < lam_num + mp.mpf(10) ** -40
    print(f"d={d}: t = lambda* certified in an interval of width 2e-70 around lambda_max(K_d) = {mp.nstr(lam_num, 30)}")
    # ---------- target: S_op - (2d - 1 - t)
    canon = SymB(d)
    lam = L.sub(L.fromK(K.const(2 * d - 1)), L.t())
    T = {}
    def add(acc, u, c):
        r = canon(u)
        if r is None or L.iszero(c):
            return
        e, rep = r
        acc[rep] = L.add(acc.get(rep, L.zero()), L.mul(c, L.fromK(K.zpow(e))))
    add(T, ((), ()), L.sub(L.fromK(K.const(2 * (d - 1))), lam))
    wp = lambda k: K.zpow(4 * k)
    def S_terms():
        out = []
        for n in range(1, d):
            cn = K.sub(K.zero(), K.inv(K.sub(K.const(1), wp(-n))))
            out += [(cn, (((0, n),), ((1, -n % d),))), (cn, (((2, -n % d),), ((1, n),))),
                    (cn, (((2, n),), ((3, -n % d),))), (K.mul(cn, wp(-n)), (((0, -n % d),), ((3, n),)))]
        return out
    for (c, u) in S_terms():
        add(T, u, L.fromK(c))
    # invariance of S_op under generators (exact, as polynomials in commuting A,B words)
    base = {}
    for (c, (a, b)) in S_terms():
        key = (reduce_w(a, d), reduce_w(b, d))
        base[key] = K.add(base.get(key, K.zero()), c)
    for gi in range(3):
        img = {}
        for (a, b), c in base.items():
            e, v = canon.gens((a, b))[gi]
            img[v] = K.add(img.get(v, K.zero()), K.mul(c, K.zpow(e)))
        ks = set(img) | set(base)
        assert all(K.iszero(K.sub(img.get(k, K.zero()), base.get(k, K.zero()))) for k in ks), f"S not invariant under generator {gi}"
    print(f"d={d}: S_op invariant under reversal, rho, sigma")
    # ---------- SOS expansion (per block; optionally in parallel worker processes)
    keep = list(cert["keep"])
    if WORKERS > 1:
        from concurrent.futures import ProcessPoolExecutor
        with ProcessPoolExecutor(max_workers=WORKERS) as ex:
            parts = list(ex.map(_block_expand, [(d, b) for b in keep]))
    else:
        parts = [_block_expand((d, b)) for b in keep]
    P = {}
    nterms = 0
    for (Pb, nt) in parts:
        nterms += nt
        for kk, v in Pb.items():
            P[kk] = L.add(P.get(kk, L.zero()), v)
    keys = set(P) | set(T)
    bad = [k for k in keys if not L.iszero(L.sub(P.get(k, L.zero()), T.get(k, L.zero())))]
    print(f"d={d}: identity over {len(keys)} symmetry classes ({nterms} expanded terms): {'OK' if not bad else 'FAILED'}", flush=True)
    assert not bad
    # ---------- positivity (exact LDL per block, interval-certified pivots)
    if WORKERS > 1:
        from concurrent.futures import ProcessPoolExecutor
        with ProcessPoolExecutor(max_workers=WORKERS) as ex:
            mins = list(ex.map(_block_ldl, [(d, b, str(lam_num)) for b in keep]))
    else:
        mins = [_block_ldl((d, b, str(lam_num))) for b in keep]
    minpiv = min(mins)
    print(f"d={d}: all Gram blocks positive definite (min certified pivot > {mp.nstr(mp.mpf(minpiv), 5)})", flush=True)
    # ---------- attainment: DKZ Bell operator on span{|kk>} equals (2d-1) - K_d exactly
    def R(g):
        a = 2 - g
        pp = [(k - 1) % d for k in range(d)]
        ee = [(-a) % N if k >= 1 else (a * (d - 1)) % N for k in range(d)]
        return pp, ee
    def T_(A):
        pp, ee = A
        pt, et = [0] * d, [0] * d
        for k in range(d):
            pt[pp[k]] = k
            et[pp[k]] = ee[k]
        return pt, et
    def mulgp(A, B):
        return [A[0][B[0][k]] for k in range(d)], [(B[1][k] + A[1][B[0][k]]) % N for k in range(d)]
    ops = [R(0), T_(R(1)), R(2), T_(R(3))]
    def powgp(A, n):
        M = (list(range(d)), [0] * d)
        for _ in range(n % d):
            M = mulgp(M, A)
        return M
    # B_op |kk> = sum over terms c * (alpha (x) beta)|kk>
    Bmat = {}
    for (c, (a, b)) in S_terms():
        Ma = (list(range(d)), [0] * d)
        for (g, n) in a:
            Ma = mulgp(Ma, powgp(ops[g], n))
        Mb = (list(range(d)), [0] * d)
        for (g, n) in b:
            Mb = mulgp(Mb, powgp(ops[g], n))
        for k in range(d):
            key = ((Ma[0][k], Mb[0][k]), k)
            Bmat[key] = K.add(Bmat.get(key, K.zero()), K.mul(c, K.zpow(Ma[1][k] + Mb[1][k])))
    for k in range(d):
        key = ((k, k), k)
        Bmat[key] = K.add(Bmat.get(key, K.zero()), K.const(2 * (d - 1)))
    for ((i, j), k), val in Bmat.items():
        if K.iszero(val):
            continue
        assert i == j, "B_op does not preserve span{|kk>}"
        # expected (2d-1) delta_{ik} - sec(pi(i-k)/(2d)) ; sec = 2/(z^m + z^-m), z = zeta_{4d}
        m = abs(i - k)
        sec = K.mul(K.const(2), K.inv(K.add(K.zpow(m), K.zpow(-m))))
        expct = K.sub(K.const(2 * d - 1) if i == k else K.zero(), sec)
        assert K.iszero(K.sub(val, expct)), "restricted Bell operator mismatch"
    for i in range(d):
        for k in range(d):
            if ((i, i), k) not in Bmat:
                raise AssertionError("missing entry")
    Sstar = 2 * d - 1 - lam_num
    Pi = (Sstar + 1) / d
    I = 4 - 2 * (d * Pi - 1) / (d - 1)
    print(f"d={d}: attainment verified (restricted DKZ Bell operator = (2d-1)1 - K_d)")
    print(f"d={d}: VERIFIED Tsirelson bound: Pi* = {mp.nstr(Pi, 30)} ; I_d* = {mp.nstr(I, 30)}")


if __name__ == "__main__":
    args = sys.argv[1:]
    if args and args[0].startswith("-j"):
        WORKERS = int(args[0][2:])
        args = args[1:]
    for d in [int(t) for t in args]:
        verify(d)
