"""
verify_tracial_iv.py -- copy of the lab's verify_tracial.py (INDEPENDENT exact checker) in which the exact LDL^T
positivity step is replaced by a rigorous INTERVAL Cholesky (mpmath.iv, outward rounding) of the exact Hermitian Gram
blocks: every entry (an exact element of Q(zeta_4d)) is enclosed by real/imaginary intervals; if all Cholesky
radicands are certified > 0, every Hermitian matrix in the enclosure, in particular Y_b, is positive definite.
The polynomial identity check and the DKZ attainment check are unchanged (exact rational arithmetic).
Original description:  verify_tracial.py -- INDEPENDENT exact checker for the maximally-entangled CGLMP certificates
cert_tracial_d{d}.pkl.  It does not import any of the construction modules; field arithmetic,
word reduction and symmetry canonicalisation are re-implemented here.

Claim verified (for the given d):
  For every maximally entangled state |Phi_D> (any D) and all projective d-outcome measurements,
      S := E m(X1-Y1) + E m(Y1-X2) + E m(X2-Y2) + E m(Y2-X1-1) >= lam,
  where lam = S of the DKZ strategy; equivalently I_d <= I_ME(d) (CGLMP value).
Proof structure checked here:
  (1) exact polynomial identity   S_op - lam = sum_b sum_{ij} (N_b Y_b N_b^+)_{ij} e_i^+ e_j
      in the group *-algebra of Z_d * Z_d * Z_d * Z_d (R1..R4, R^d = 1), modulo the linear span of
      {w - g.w} for g in the group generated by cyclic rotation, reversal, rho, sigma (with phases);
      valid for tracial functionals invariant under these symmetries; any tracial state can be
      symmetrised without changing S (S_op is invariant: also checked here).
  (2) every Y_b is positive definite (exact Hermitian LDL^T over Q(zeta_{4d}); pivots are real field
      elements, their signs are certified with mpmath interval arithmetic).
  (3) lam is attained by the DKZ strategy (exact evaluation) and equals d*Pi_ME - 1 with
      Pi_ME = 2 - (1/d^2) sum_{k,l} sec(pi(k-l)/(2d)) (checked to 60 digits).
Maximally entangled -> tracial:  <Phi_D| A (x) B |Phi_D> = Tr(A B^T)/D ; R1=A1, R2=B1^T, R3=A2, R4=B2^T.
"""
import sys
import pickle
try:                                   # exact rationals: gmpy2.mpq if available (fast), else fractions
    from gmpy2 import mpq as Fraction
except ImportError:
    from fractions import Fraction
import mpmath as mp


# ---------------- independent cyclotomic field (Fraction coefficients) ----------------
class CF:
    def __init__(self, N):
        self.N = N
        # cyclotomic polynomial by repeated division, Fraction arithmetic
        def cyc(n):
            num = [Fraction(-1)] + [Fraction(0)] * (n - 1) + [Fraction(1)]
            for dd in range(1, n):
                if n % dd == 0:
                    den = cyc(dd)
                    q = [Fraction(0)] * (len(num) - len(den) + 1)
                    r = num[:]
                    for i in range(len(r) - len(den), -1, -1):
                        c = r[i + len(den) - 1] / den[-1]
                        q[i] = c
                        for j in range(len(den)):
                            r[i + j] -= c * den[j]
                    num = q
            return num
        self.P = cyc(N)
        self.n = len(self.P) - 1

    def red(self, poly):
        p = list(poly)
        n = self.n
        for k in range(len(p) - 1, n - 1, -1):
            c = p[k]
            if c:
                for j in range(n + 1):
                    p[k - n + j] -= c * self.P[j]
        p = p[:n] + [Fraction(0)] * max(0, n - len(p))
        return tuple(p[:n])

    def zpow(self, k):
        k %= self.N
        return self.red([Fraction(0)] * k + [Fraction(1)])

    def add(self, a, b):
        return tuple(x + y for x, y in zip(a, b))

    def sub(self, a, b):
        return tuple(x - y for x, y in zip(a, b))

    def mul(self, a, b):
        prod = [Fraction(0)] * (2 * self.n)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        prod[i + j] += x * y
        return self.red(prod)

    def conj(self, a):
        out = [Fraction(0)] * self.n
        for k, x in enumerate(a):
            if x:
                zk = self.zpow(-k)
                for j in range(self.n):
                    out[j] += x * zk[j]
        return tuple(out)

    def zero(self):
        return tuple([Fraction(0)] * self.n)

    def const(self, q):
        return tuple([Fraction(q)] + [Fraction(0)] * (self.n - 1))

    def iszero(self, a):
        return all(x == 0 for x in a)

    def inv(self, a):
        # solve multiplication-matrix system
        n = self.n
        cols = [self.mul(a, tuple(Fraction(1 if j == k else 0) for j in range(n))) for k in range(n)]
        A = [[cols[j][i] for j in range(n)] + [Fraction(1 if i == 0 else 0)] for i in range(n)]
        for c in range(n):
            p = next(r for r in range(c, n) if A[r][c] != 0)
            A[c], A[p] = A[p], A[c]
            pv = A[c][c]
            A[c] = [v / pv for v in A[c]]
            for r in range(n):
                if r != c and A[r][c] != 0:
                    f = A[r][c]
                    A[r] = [vr - f * vc for vr, vc in zip(A[r], A[c])]
        return tuple(A[i][n] for i in range(n))

    def interval(self, a, prec=200):
        """rigorous enclosure (mpmath.iv) of the complex value, returned as (re_iv, im_iv)."""
        iv = mp.iv
        iv.prec = prec
        re = iv.mpf(0)
        im = iv.mpf(0)
        for k, x in enumerate(a):
            if x:
                ang = 2 * iv.pi * k / self.N
                q = iv.mpf(x.numerator) / x.denominator
                re += q * iv.cos(ang)
                im += q * iv.sin(ang)
        return re, im


def from_cyclo(F, x):
    """convert (int tuple, den) element from the certificate pickle to CF tuple."""
    a, den = x
    return tuple(Fraction(v, den) for v in a)


# ---------------- words: letters (g, n), g in 0..3, n in 1..d-1 ----------------
def reduce_w(w, d):
    out = []
    for (g, n) in w:
        n %= d
        if n == 0:
            continue
        if out and out[-1][0] == g:
            m = (out[-1][1] + n) % d
            out.pop()
            if m:
                out.append((g, m))
        else:
            out.append((g, n))
    return tuple(out)


def cyc_reduce(w, d):
    w = list(reduce_w(w, d))
    while len(w) >= 2 and w[0][0] == w[-1][0]:
        m = (w[0][1] + w[-1][1]) % d
        g = w[0][0]
        w = w[1:-1]
        if m:
            w = [(g, m)] + w
        w = list(reduce_w(tuple(w), d))
    return tuple(w)


def canon_cyc(w, d):
    w = cyc_reduce(w, d)
    if len(w) <= 1:
        return w
    return min(w[i:] + w[:i] for i in range(len(w)))


def adj(w, d):
    return tuple((g, (-n) % d) for (g, n) in reversed(w))


class SymCanon:
    """L(w) = zeta^e L(rep) for symmetric tracial L; returns (e, rep) or None if L(w)=0 forced."""

    def __init__(self, d):
        self.d, self.N = d, 4 * d
        self.memo = {}

    def gens(self, u):
        d, N = self.d, self.N
        out = [(0, canon_cyc(tuple(reversed(u)), d))]
        e, v = 0, []
        for (g, n) in u:
            if g == 3:
                e += 4 * n
                v.append((0, n))
            else:
                v.append((g + 1, n))
        out.append((e % N, canon_cyc(tuple(v), d)))
        out.append((0, canon_cyc(tuple((3 - g, (-n) % d) for (g, n) in u), d)))
        return out

    def __call__(self, w):
        d, N = self.d, self.N
        w0 = canon_cyc(w, d)
        if w0 in self.memo:
            return self.memo[w0]
        seen = {w0: 0}
        stack = [w0]
        bad = False
        while stack:
            u = stack.pop()
            for (e, v) in self.gens(u):
                ev = (seen[u] + e) % N
                if v in seen:
                    if seen[v] != ev:
                        bad = True
                else:
                    seen[v] = ev
                    stack.append(v)
        if bad:
            res = None
        else:
            rep = min(seen)
            res = (seen[rep], rep)
        for u, eu in seen.items():
            if res is None:
                self.memo[u] = None
            else:
                # L(u) = zeta^{-eu} L(w0) = zeta^{res[0]-eu} L(rep)
                self.memo[u] = ((res[0] - eu) % N, res[1])
        return self.memo[w0]


def add_to(F, acc, canon, w, c):
    r = canon(w)
    if r is None or F.iszero(c):
        return
    e, rep = r
    val = F.mul(c, F.zpow(e))
    acc[rep] = F.add(acc.get(rep, F.zero()), val)


def verify(d):
    cert = pickle.load(open(f"cert_tracial_d{d}.pkl", "rb"))
    assert cert["d"] == d
    N = 4 * d
    F = CF(N)
    canon = SymCanon(d)
    lam = from_cyclo(F, cert["lam"])
    # ---- target polynomial T = S_op - lam
    T = {}
    add_to(F, T, canon, (), F.sub(F.const(2 * (d - 1)), lam))
    w_ = lambda k: F.zpow(4 * k)
    for n in range(1, d):
        cn = F.sub(F.zero(), F.inv(F.sub(F.const(1), w_(-n))))    # -1/(1 - w^-n)
        for (c, word) in [(cn, ((0, n), (1, -n))), (cn, ((1, n), (2, -n))), (cn, ((2, n), (3, -n))),
                          (F.mul(cn, w_(-n)), ((3, n), (0, -n)))]:
            add_to(F, T, canon, reduce_w(word, d), c)
    # ---- invariance of S_op under the generators (as polynomials modulo cyclic equivalence only)
    def S_terms():
        out = {}
        for n in range(1, d):
            cn = F.sub(F.zero(), F.inv(F.sub(F.const(1), w_(-n))))
            for (c, word) in [(cn, ((0, n), (1, -n))), (cn, ((1, n), (2, -n))), (cn, ((2, n), (3, -n))),
                              (F.mul(cn, w_(-n)), ((3, n), (0, -n)))]:
                k = canon_cyc(reduce_w(word, d), d)
                out[k] = F.add(out.get(k, F.zero()), c)
        return out
    S0 = S_terms()
    for gname in ("rho", "sigma", "rev"):
        img = {}
        for k, c in S0.items():
            if gname == "rho":
                e, v = 0, []
                for (g, n) in k:
                    if g == 3:
                        e += 4 * n
                        v.append((0, n))
                    else:
                        v.append((g + 1, n))
                kk, cc = canon_cyc(tuple(v), d), F.mul(c, F.zpow(e))
            elif gname == "sigma":
                kk, cc = canon_cyc(tuple((3 - g, (-n) % d) for (g, n) in k), d), c
            else:
                kk, cc = canon_cyc(tuple(reversed(k)), d), c
            img[kk] = F.add(img.get(kk, F.zero()), cc)
        keys = set(img) | set(S0)
        assert all(F.iszero(F.sub(img.get(k, F.zero()), S0.get(k, F.zero()))) for k in keys), gname
    print(f"d={d}: S_op invariant under rho, sigma, reversal (mod cyclic)")
    # ---- SOS side
    P = {}
    keep = cert["keep"]
    ntot = 0
    for b in keep:
        lab, els, _ent = cert["bdata"][b]
        ker = [[from_cyclo(F, x) for x in col] for col in cert["kernels"][b]]
        Y = [[from_cyclo(F, x) for x in row] for row in cert["Y"][b]]
        k = len(ker)
        n = len(els)
        # Hermiticity of Y
        for i in range(k):
            for j in range(k):
                assert F.iszero(F.sub(Y[i][j], F.conj(Y[j][i]))), "Y not Hermitian"
        # X = N Y N^+
        NY = [[F.zero() for _ in range(k)] for _ in range(n)]
        for a in range(n):
            for c in range(k):
                acc = F.zero()
                for r in range(k):
                    if not F.iszero(ker[r][a]) and not F.iszero(Y[r][c]):
                        acc = F.add(acc, F.mul(ker[r][a], Y[r][c]))
                NY[a][c] = acc
        X = [[F.zero() for _ in range(n)] for _ in range(n)]
        for a in range(n):
            for bb in range(n):
                acc = F.zero()
                for c in range(k):
                    if not F.iszero(NY[a][c]) and not F.iszero(ker[c][bb]):
                        acc = F.add(acc, F.mul(NY[a][c], F.conj(ker[c][bb])))
                X[a][bb] = acc
        # X_{ab} multiplies e_a^+ e_b ?  convention: sum_{a,b} conj(x_a) X_ab x_b with x = (e_1..e_n):
        # the certificate Gram in the builder pairs <e_i|e_j> with Y_ij (moment matrix M_ij = L(e_i^+ e_j)),
        # and tr(X M) = sum_{ij} X_ij M_ji = sum_{ij} X_ij L(e_j^+ e_i).
        els_c = [[(from_cyclo(F, c), w) for (c, w) in el] for el in els]
        for i in range(n):
            for j in range(n):
                if F.iszero(X[i][j]):
                    continue
                # term X_ij * e_j^+ e_i
                for (cj, wj) in els_c[j]:
                    for (ci, wi) in els_c[i]:
                        c = F.mul(X[i][j], F.mul(F.conj(cj), ci))
                        add_to(F, P, canon, reduce_w(adj(wj, d) + wi, d), c)
                        ntot += 1
    keys = set(P) | set(T)
    bad = [k for k in keys if not F.iszero(F.sub(P.get(k, F.zero()), T.get(k, F.zero())))]
    print(f"d={d}: identity check over {len(keys)} symmetry classes ({ntot} expanded terms): "
          f"{'OK' if not bad else 'FAILED on ' + str(len(bad)) + ' classes'}")
    assert not bad
    # ---- positivity: rigorous interval Cholesky of each Y_b
    iv = mp.iv
    iv.prec = 200
    minpiv = None
    for b in keep:
        Y = [[from_cyclo(F, x) for x in row] for row in cert["Y"][b]]
        k = len(Y)
        # exact Hermiticity
        for i in range(k):
            for j in range(k):
                assert F.iszero(F.sub(Y[i][j], F.conj(Y[j][i]))), "Y not Hermitian"
        A = [[F.interval(Y[i][j], prec=200) for j in range(k)] for i in range(k)]   # (re, im) intervals
        L = [[(iv.mpf(0), iv.mpf(0)) for _ in range(k)] for _ in range(k)]
        for j in range(k):
            s_re = A[j][j][0]
            for q in range(j):
                lr, li = L[j][q]
                s_re = s_re - (lr * lr + li * li)
            assert s_re.a > 0, f"interval Cholesky failed: block {b} col {j} radicand {s_re}"
            minpiv = s_re.a if minpiv is None else min(minpiv, s_re.a)
            ljj = iv.sqrt(s_re)
            L[j][j] = (ljj, iv.mpf(0))
            for i in range(j + 1, k):
                ar, ai = A[i][j]
                for q in range(j):
                    xr, xi = L[i][q]
                    yr, yi = L[j][q]
                    # x * conj(y)
                    ar = ar - (xr * yr + xi * yi)
                    ai = ai - (xi * yr - xr * yi)
                L[i][j] = (ar / ljj, ai / ljj)
    print(f"d={d}: all {len(keep)} Gram blocks positive definite (rigorous interval Cholesky, min radicand > {mp.nstr(minpiv, 5)})")
    # ---- value of lam: closed form and DKZ attainment
    mp.mp.dps = 60
    lamv = F.interval(lam)[0]
    Pi_me = 2 - mp.fsum(mp.sec(mp.pi * (k - l) / (2 * d)) for k in range(d) for l in range(d)) / d ** 2
    S_me = d * Pi_me - 1
    assert abs(mp.mpf(lamv.mid) - S_me) < mp.mpf(10) ** -50, (lamv, S_me)
    # DKZ attainment (independent evaluation with generalised permutations)
    def R(g):
        a = 2 - g
        p = [(k - 1) % d for k in range(d)]
        e = [(-a) % N if k >= 1 else (a * (d - 1)) % N for k in range(d)]
        return p, e
    def mulgp(A, B):
        return [A[0][B[0][k]] for k in range(d)], [(B[1][k] + A[1][B[0][k]]) % N for k in range(d)]
    def word_trace(w):
        M = (list(range(d)), [0] * d)
        for (g, n) in w:
            for _ in range(n % d):
                M = mulgp(M, R(g))
        tot = F.zero()
        for k in range(d):
            if M[0][k] == k:
                tot = F.add(tot, F.zpow(M[1][k]))
        return F.mul(tot, F.const(Fraction(1, d)))
    val = F.const(2 * (d - 1))
    for n in range(1, d):
        cn = F.sub(F.zero(), F.inv(F.sub(F.const(1), w_(-n))))
        for (c, word) in [(cn, ((0, n), (1, -n))), (cn, ((1, n), (2, -n))), (cn, ((2, n), (3, -n))),
                          (F.mul(cn, w_(-n)), ((3, n), (0, -n)))]:
            val = F.add(val, F.mul(c, word_trace(reduce_w(word, d))))
    assert F.iszero(F.sub(val, lam)), "lam is not the DKZ value"
    Pi = (S_me + 1) / d
    I = 4 - 2 * (d * Pi - 1) / (d - 1)
    print(f"d={d}: lam = S_DKZ exactly;  Pi_ME = {mp.nstr(Pi, 30)} ;  I_ME = {mp.nstr(I, 30)}")
    print(f"d={d}: VERIFIED: max CGLMP value over maximally entangled states (any dimension) = I_ME")
    return True


if __name__ == "__main__":
    for d in [int(t) for t in sys.argv[1:]]:
        verify(d)
